version: 0.0
os: linux
files:
  - source: ./frontend
    destination: /home/ubuntu/devops-basics/frontend
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: backend/scripts/install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: backend/scripts/start
    - location: frontend/scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: frontend/scripts/start.sh
      timeout: 300
      runas: ubuntu
