version: "3.8"
services:
  web:
      build: ./frontend
      ports:
          - "3001:3001"
  api:
    build: ./backend
    ports:
        - 3000:3000
  postgres:
    image: postgres:14
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      